name: wormlab3d

channels:
  - conda-forge
  - pytorch
  - bioconda

dependencies:
  - python = 3.9
  - av = 8.0
  - fastcluster = 1.2.6
  - ffmpeg-python = 0.2
  - flask = 2.0
  - flask-wtf = 1.0
  - gunicorn = 20.1
  - h5py = 3.2
  - matplotlib = 3.4
  - mayavi = 4.7
  - mongoengine = 0.22
  - numpy = 1.20
  - opencv = 4.5
  - pims = 0.5
  - progress = 1.6
  - pymongo = 3.11
  - pymoo = 0.6
  - pyro-ppl = 1.8
  - python-blosc = 1.10
  - python-dotenv = 0.16
  - pytorch = 1.10
  - scikit-image = 0.18
  - scikit-learn = 0.24
  - scipy = 1.8
  - tensorboard = 2.4
  - torchvision = 0.11
  - pip